routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'as' => 'app.',
], function () {
    Route::get('/', 'MagazineController@index')->name('index');

    Route::get('/css/{editionSlug}/compiled.css', 'MagazineController@compiledCss')->name('css');
    Route::get('images/{image}', 'MagazineController@getImages')->name('images');
    Route::get('media/{medium}', 'MagazineController@getMedia')->name('media');

    Route::get('magazine/{editionSlug}', 'MagazineController@getEdition')->name('get-edition');
    Route::get('/{editionSlug}', 'MagazineController@view')->name('view');
});

Route::group(['namespace' => 'Auth', 'prefix' => 'auth', 'as' => 'auth.'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('show-login');
    Route::post('login/{guard?}', 'LoginController@login')->name('login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group([
    'middleware' => 'auth:admin',
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::resource('edition', 'OrganizeController')->only(['store', 'edit', 'update', 'destroy']);

    Route::group(['prefix' => '{edition}'], function () {
        Route::resource('page', 'PageController')->except(['edit']);
        // Another route for detail page
        Route::group(['as' => 'page.', 'prefix' => 'page/{page}'], function () {
            Route::post('update-image', 'PageController@updateImage')->name('update-image');
            Route::post('update-content', 'PageController@updateContent')->name('update-content');
        });

        Route::resource('media', 'MediaController')->only(['index', 'store', 'update', 'destroy']);
        Route::get("/pdf/create", "MediaController@createPdf")->name("media.create-pdf");
        Route::resource('style', 'StyleController')->only(['index', 'store', 'update', 'destroy']);
    });
});

app/Models/Contents/Edition.php
<?php

namespace App\Models\Contents;

use App\Models\Account\Admin;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use App\Core\HashId\Eloquent\HashableId;
use Illuminate\Support\Facades\Storage;

class Edition extends Model
{
    use HashableId;

    protected static function boot()
    {
        parent::boot();

        self::creating(function ($model) {
            $model->slug = str_slug($model->name);
        });

        self::addGlobalScope(function (Builder $builder) {
            return $builder->orderBy('created_at', 'desc');
        });
    }

    protected $table = 'editions';

    protected $with = ['languages'];

    protected $appends = ['hash', 'cover'];

    protected $fillable = [
        'name', 'released',
    ];

    protected $casts = [
        'released' => 'boolean',
    ];

    public function style()
    {
        return $this->hasMany(Style::class, 'edition_id', 'id');
    }

    public function author()
    {
        return $this->belongsTo(Admin::class, 'admin_id', 'id');
    }

    public function pages()
    {
        return $this->hasMany(Page::class, 'edition_id', 'id');
    }

    public function languages()
    {
        return $this->belongsToMany(Language::class, 'edition_language');
    }

    public function media()
    {
        return $this->hasMany(Media::class, 'edition_id', 'id');
    }

    public function scopeReleased (Builder $query)
    {
        return $query->where('released', true);
    }

    public function getCoverAttribute()
    {
        $firstPage = $this->pages()
            ->where('pages.order', 1)
            ->first()
            ->image()
            ->first();

        if (! is_null($firstPage)) {
            return $firstPage->thumb["id"];
        }

        return $firstPage;
    }

    public function getPdfAttribute()
    {
        return $this
            ->media()
            ->where("type", "pdf")
            ->select(\DB::raw("substr(title, -2, 5) as lang"), "uuid as src")
            ->get();

    }

    public function getAttachedMediaAttribute ()
    {
        return $this
            ->media()
            ->whereNotIn("type", ["apk", "pdf", "image"])
            ->select("src", "type", "title")
            ->get();
    }
}

app/Http/Controllers/Api/EditionsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Contents\Edition;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\EditionResource;

class EditionsController extends Controller
{
    public function index ()
    {
        $editions = Edition::released()->latest()->get();
        return EditionResource::collection($editions);
    }
}

resources/views/backoffice/components/editions/list.blade.php
<table class="table is-fullwidth">
  <thead>
  <tr>
    <th>Nama</th>
    <th>Bahasa</th>
    <th>Status</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  @each('backoffice.components.editions.list_item', $editions, 'edition', 'backoffice.components.editions.list_empty')
  </tbody>
</table>

resources/views/backoffice/components/editions/list_empty.blade.php
<tr>
  <td colspan="4" class="has-text-centered">
    Belum ada edisi
  </td>
</tr>

resources/views/backoffice/components/editions/list_item.blade.php
<tr>
  <td>{{ $edition->name }}</td>
  <td>{{ $edition->languages->implode('code', ', ') }}</td>
  <td>
    @if( $edition->released )
      <span class="tag is-link">Telah Dirilis</span>
    @else
      <span class="tag is-danger">Belum Dirilis</span>
    @endif
  </td>
  <td>
    <form action="{{ route('admin.edition.destroy', [ 'edition' => $edition->hash ]) }}"
          style="display: none;" method="post" id="delete-form-{{ $edition->hash }}">
      {{ csrf_field() }}
      {{ method_field('delete') }}
    </form>
    <a href="javascript:void(0)" class="modal-button" data-target="modal-option-{{ $edition->hash }}">
            <span class="icon has-text-info">
              <span class="ion-ios-paper-outline"></span>
            </span>
    </a>
    <a href="{{ route('admin.edition.edit', [ 'id' => $edition->hash ]) }}">
            <span class="icon has-text-warning">
              <span class="ion-edit"></span>
            </span>
    </a>
    <a href="javascript:void(0)" class="swal-warn" data-target="#delete-form-{{ $edition->hash }}"
       data-title="Hapus {{ $edition->name }} ? " data-subtitle="Data tidak bisa kembali">
            <span class="icon has-text-danger">
              <span class="ion-trash-b"></span>
            </span>
    </a>
  </td>
</tr>

@push('modals')
  <div class="modal" id="modal-option-{{ $edition->hash }}">
    <div class="modal-background"></div>
    <div class="modal-card">
      <section class="modal-card-body">
        <a class="button is-danger is-inverted"
           href="{{ route('admin.media.index', [ 'edition' => $edition->hash ]) }}">Media</a>
        <a class="button is-success is-inverted"
           href="{{ route('admin.style.index', [ 'edition' => $edition->hash ]) }}">Stylesheet</a>
        <a class="button is-link is-inverted"
           href="{{ route('admin.page.index', [ 'edition' => $edition->hash ]) }}">Halaman</a>
      </section>
    </div>
  </div>
@endpush