routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'as' => 'app.',
], function () {
    Route::get('/', 'MagazineController@index')->name('index');

    Route::get('/css/{editionSlug}/compiled.css', 'MagazineController@compiledCss')->name('css');
    Route::get('images/{image}', 'MagazineController@getImages')->name('images');
    Route::get('media/{medium}', 'MagazineController@getMedia')->name('media');

    Route::get('magazine/{editionSlug}', 'MagazineController@getEdition')->name('get-edition');
    Route::get('/{editionSlug}', 'MagazineController@view')->name('view');
});

Route::group(['namespace' => 'Auth', 'prefix' => 'auth', 'as' => 'auth.'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('show-login');
    Route::post('login/{guard?}', 'LoginController@login')->name('login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group([
    'middleware' => 'auth:admin',
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::resource('edition', 'OrganizeController')->only(['store', 'edit', 'update', 'destroy']);

    Route::group(['prefix' => '{edition}'], function () {
        Route::resource('page', 'PageController')->except(['edit']);
        // Another route for detail page
        Route::group(['as' => 'page.', 'prefix' => 'page/{page}'], function () {
            Route::post('update-image', 'PageController@updateImage')->name('update-image');
            Route::post('update-content', 'PageController@updateContent')->name('update-content');
        });

        Route::resource('media', 'MediaController')->only(['index', 'store', 'update', 'destroy']);
        Route::get("/pdf/create", "MediaController@createPdf")->name("media.create-pdf");
        Route::resource('style', 'StyleController')->only(['index', 'store', 'update', 'destroy']);
    });
});

resources/views/backoffice/components/pages/list.blade.php
<h3>Halaman Edisi : {{ $edition->name }}</h3>
<a href="javascript:void(0)" class="button is-link is-pulled-right modal-button" data-target="modal-add-page">
  <span class="ion-plus-round"></span>&nbsp;&nbsp; Halaman
</a>
<div class="is-clearfix" style="margin-bottom: 20px"></div>
@each('backoffice.components.pages.list_item', $pages, 'page', 'backoffice.components.pages.list_empty')
{{ $pages->links() }}

resources/views/backoffice/components/pages/list_empty.blade.php
<div class="column">
    <p class="has-text-centered">Belum ada halaman</p>
</div>

resources/views/backoffice/components/pages/list_item.blade.php
<div class="column">
  <div class="card">
    <header class="card-header">
      <p class="card-header-title">
        {{ $page->title }}
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        Halaman : {{ $page->order }}
        <div>
          <a href="javascript:void(0)" class="button modal-button" data-target="modal-page-edit-{{ $page->id }}">
            <span class="icon">
              <span class="ion-edit"></span>
            </span>
            &nbsp; Edit
          </a>
        </div>
      </div>
    </div>
    <footer class="card-footer">
      <a href="{{ route('admin.page.show', [ 'edition' => $page->edition->hash, 'page' => $page->id ]) }}"
         class="card-footer-item is-warning">Kelola</a>
      <form action="{{ route('admin.page.destroy', ['edition' => $page->edition->hash, 'page' => $page->id]) }}"
            id="delete-page-{{ $page->id }}" style="display: none" method="post">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
      </form>
      <a href="javascript:void(0)" class="card-footer-item swal-warn" data-target="#delete-page-{{ $page->id }}"
         data-title="Hapus {{ $page->title }}" data-subtitle="Data tidak dapat kembali">Hapus</a>
    </footer>
  </div>
</div>


@push('modals')
  <div class="modal" id="modal-page-edit-{{ $page->id }}">
    <div class="modal-background"></div>
    <div class="modal-card">
      <section class="modal-card-body">
        <form action="{{ route('admin.page.update', ['edition' => $page->edition->hash, 'page' => $page->id]) }}" method="post">
          {{ csrf_field() }}
          {{ method_field('PUT') }}
          <div class="field">
            <label class="label">Judul Halaman</label>
            <div class="control">
              <input class="input" type="text" placeholder="Cover" name="title" value="{{ $page->title }}">
            </div>
          </div>
          <div class="field">
            <label class="label">Urutan Halaman</label>
            <div class="control">
              <input class="input" type="number" name="order" value="{{ $page->order }}">
            </div>
          </div>
          <button class="button" type="submit">Simpan</button>
        </form>
      </section>
    </div>
  </div>
@endpush