routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'as' => 'app.',
], function () {
    Route::get('/', 'MagazineController@index')->name('index');

    Route::get('/css/{editionSlug}/compiled.css', 'MagazineController@compiledCss')->name('css');
    Route::get('images/{image}', 'MagazineController@getImages')->name('images');
    Route::get('media/{medium}', 'MagazineController@getMedia')->name('media');

    Route::get('magazine/{editionSlug}', 'MagazineController@getEdition')->name('get-edition');
    Route::get('/{editionSlug}', 'MagazineController@view')->name('view');
});

Route::group(['namespace' => 'Auth', 'prefix' => 'auth', 'as' => 'auth.'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('show-login');
    Route::post('login/{guard?}', 'LoginController@login')->name('login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group([
    'middleware' => 'auth:admin',
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::resource('edition', 'OrganizeController')->only(['store', 'edit', 'update', 'destroy']);

    Route::group(['prefix' => '{edition}'], function () {
        Route::resource('page', 'PageController')->except(['edit']);
        // Another route for detail page
        Route::group(['as' => 'page.', 'prefix' => 'page/{page}'], function () {
            Route::post('update-image', 'PageController@updateImage')->name('update-image');
            Route::post('update-content', 'PageController@updateContent')->name('update-content');
        });

        Route::resource('media', 'MediaController')->only(['index', 'store', 'update', 'destroy']);
        Route::get("/pdf/create", "MediaController@createPdf")->name("media.create-pdf");
        Route::resource('style', 'StyleController')->only(['index', 'store', 'update', 'destroy']);
    });
});

resources/views/backoffice/layouts/pages/index.blade.php
@extends('backoffice.layouts.app')

@section('header')
  Dasbor
@endsection

@push('modals')
  <div class="modal" id="modal-add-page">
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <h2>Tambah Halaman</h2>
      </header>
      <section class="modal-card-body">
        <form action="{{ route('admin.page.store', [ 'edition' => $edition->hash ]) }}" method="post" id="store-page">
          {{ csrf_field() }}
          <div class="field">
            <label class="label">Judul Halaman</label>
            <div class="control">
              <input class="input" type="text" placeholder="Cover" name="title">
            </div>
          </div>
          <div class="field">
            <label class="label">Urutan Halaman</label>
            <div class="control">
              <input class="input" type="number" name="order">
            </div>
          </div>
        </form>
      </section>
      <footer class="modal-card-foot">
        <button class="button is-success" onclick="document.getElementById('store-page').submit()">Simpan</button>
        <button class="button modal-dismiss">Batal</button>
      </footer>
    </div>
  </div>
@endpush

@section('content')
  <div class="column is-6">
    <div class="box has-shadow">
      <div class="content">
        @include('backoffice.components.editions.list')
      </div>
    </div>
  </div>
  <div class="column is-6">
    <div class="box has-shadow">
      <div class="content">
        @include('backoffice.components.pages.list')
      </div>
    </div>
  </div>
@endsection

resources/views/backoffice/layouts/pages/show.blade.php
@extends('backoffice.layouts.app')

@section('header')
  Kelola Halaman {{ $page->title }} Edisi {{ $edition->name }}
@endsection

@section('content')
  <div id="detail-edition" style="width: 100%"
       data-url="{&quot;image&quot;:&quot;{{ route('admin.page.update-image', ['edition' => $edition->hash, 'page' => $page->id]) }}&quot;,&quot;content&quot;:&quot;{{ route('admin.page.update-content', ['edition' => $edition->hash, 'page' => $page->id]) }}&quot;,&quot;imageUrl&quot;:&quot;{{ route('app.images', ['image' => 'uuid' ]) }}&quot;}"
       data-edition="{{ $edition }}" data-page="{{ $page }}" ></div>
@endsection

@push('styles')
  <link rel="stylesheet" type="text/css" href="{{ route('app.css', ['editionSlug' => $edition->slug]) }}">
@endpush

@push('scripts')
  <script src="{{ asset('js/admin/detail-edition.js') }}"></script>
@endpush