routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'as' => 'app.',
], function () {
    Route::get('/', 'MagazineController@index')->name('index');

    Route::get('/css/{editionSlug}/compiled.css', 'MagazineController@compiledCss')->name('css');
    Route::get('images/{image}', 'MagazineController@getImages')->name('images');
    Route::get('media/{medium}', 'MagazineController@getMedia')->name('media');

    Route::get('magazine/{editionSlug}', 'MagazineController@getEdition')->name('get-edition');
    Route::get('/{editionSlug}', 'MagazineController@view')->name('view');
});

Route::group(['namespace' => 'Auth', 'prefix' => 'auth', 'as' => 'auth.'], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('show-login');
    Route::post('login/{guard?}', 'LoginController@login')->name('login');
    Route::post('logout', 'LoginController@logout')->name('logout');
});

Route::group([
    'middleware' => 'auth:admin',
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::resource('edition', 'OrganizeController')->only(['store', 'edit', 'update', 'destroy']);

    Route::group(['prefix' => '{edition}'], function () {
        Route::resource('page', 'PageController')->except(['edit']);
        // Another route for detail page
        Route::group(['as' => 'page.', 'prefix' => 'page/{page}'], function () {
            Route::post('update-image', 'PageController@updateImage')->name('update-image');
            Route::post('update-content', 'PageController@updateContent')->name('update-content');
        });

        Route::resource('media', 'MediaController')->only(['index', 'store', 'update', 'destroy']);
        Route::get("/pdf/create", "MediaController@createPdf")->name("media.create-pdf");
        Route::resource('style', 'StyleController')->only(['index', 'store', 'update', 'destroy']);
    });
});

resources/views/client/layouts/index.blade.php
@extends('client.app')

@section('content')
<nav class="navbar has-shadow" role="navigation" aria-label="dropdown main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <strong>SEMANGGI </strong> &nbsp; Digital Magazine
      </a>
    </div>
  </nav>
  <div class="container" style="margin-top:5%">
  <h1 class="title">Daftar Edisi</h1>
    <section class="columns is-multiline">
      @foreach($editions as $edition)
      <div class="column is-4">
        <a href="{{ route('app.view', [ 'editionSlug' => $edition->slug ]) }}">
          <div class="box">
            <article class="media">
              <div class="media-left">
                <figure class="image is-64x64">
                  <img src="{{ $edition->cover }}" alt="Cover">
                </figure>
              </div>
              <div class="media-content" style="margin-left: 72px; padding-bottom:12px">
                <div class="content">
                  <h4>{{ $edition->name }}</h1>
                  Bahasa : {{ $edition->languages->implode('code', ', ') }}
                  <!-- <br> Terakhir diperbarui pada {{ $edition->updated_at->diffForHumans()}} -->
                </div>
              </div>
            </article>
            <div class="is-clearfix"></div>
          </div>
        </a>
      </div>
      @endforeach
    </section>
  </div>
@endsection

resources/views/client/layouts/show.blade.php
@extends('client.app')

@section('content')
  <div id="root"></div>
@endsection

@push('scripts')
  <script>
    window.data = {
      url: {
        image   : "{{ route('app.images', ['image' => 'uuid']) }}",
        edition : "{{ route('app.get-edition', ['editionSlug' => $edition->slug]) }}"
      }
    }

    window.audio = {!! $audio !!}

    window.files = {!! $files !!}
  </script>
  <script src="{{ asset('js/particles.min.js') }}"></script>
  <script src="{{ asset('js/magazine.js') }}"></script>
@endpush

@push('styles')
  <link rel="stylesheet" href="{{ route('app.css', ['editionSlug' => $edition->slug]) }}">
  <style type="text/css">
    html, body {
      overflow: hidden;
      width: 100%;
      height: 100vh;
      position: relative;
    }

    body {
      background: #fff;
    }
  </style>
@endpush